const cacheName = "fantasy-inventory-v30";
const assets = [
  "./",
  "./index.html",
  "./login.html",
  "./styles.css",
  "./styles.css?v=6",
  "./styles.css?v=7",
  "./styles.css?v=8",
  "./styles.css?v=9",
  "./styles.css?v=10",
  "./styles.css?v=11",
  "./styles.css?v=12",
  "./styles.css?v=13",
  "./styles.css?v=14",
  "./styles.css?v=15",
  "./styles.css?v=16",
  "./styles.css?v=17",
  "./styles.css?v=18",
  "./styles.css?v=19",
  "./styles.css?v=20",
  "./styles.css?v=21",
  "./styles.css?v=22",
  "./styles.css?v=23",
  "./styles.css?v=24",
  "./styles.css?v=25",
  "./styles.css?v=26",
  "./styles.css?v=27",
  "./styles.css?v=28",
  "./styles.css?v=29",
  "./styles.css?v=30",
  "./app.js",
  "./app.js?v=6",
  "./app.js?v=7",
  "./app.js?v=8",
  "./app.js?v=9",
  "./app.js?v=10",
  "./app.js?v=11",
  "./app.js?v=12",
  "./app.js?v=13",
  "./app.js?v=14",
  "./app.js?v=15",
  "./app.js?v=16",
  "./app.js?v=17",
  "./app.js?v=18",
  "./app.js?v=19",
  "./app.js?v=20",
  "./app.js?v=21",
  "./app.js?v=22",
  "./app.js?v=23",
  "./app.js?v=24",
  "./app.js?v=25",
  "./app.js?v=26",
  "./app.js?v=27",
  "./app.js?v=28",
  "./app.js?v=29",
  "./app.js?v=30",
  "./manifest.webmanifest",
  "./apple-touch-icon.png",
  "./assets/forest-poster-v1.png",
  "./assets/forest-premium-v2.png",
  "./assets/poster-butterfly-a.png",
  "./assets/poster-butterfly-b.png",
  "./assets/poster-butterfly-c.png",
  "./assets/ui/btn-add-blank.png",
  "./assets/ui/btn-add-cost.png",
  "./assets/ui/btn-ai.png",
  "./assets/ui/btn-capture.png",
  "./assets/ui/btn-cost.png",
  "./assets/ui/btn-danger.png",
  "./assets/ui/btn-excel.png",
  "./assets/ui/btn-history.png",
  "./assets/ui/btn-login.png",
  "./assets/ui/btn-logout.png",
  "./assets/ui/btn-new-snapshot.png",
  "./assets/ui/btn-pdf.png",
  "./assets/ui/btn-reset.png",
  "./assets/ui/drop-capture.png",
  "./assets/ui/pill-1.png",
  "./assets/ui/pill-2.png",
  "./assets/ui/pill-3.png",
  "./assets/ui/pill-4.png",
  "./icons/apple-touch-icon.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-192.svg",
  "./icons/icon-512.svg"
];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(cacheName).then((cache) => cache.addAll(assets)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((key) => key !== cacheName).map((key) => caches.delete(key))))
  );
});

self.addEventListener("fetch", (event) => {
  event.respondWith(caches.match(event.request).then((response) => response || fetch(event.request)));
});
